name: 'GitHub Readme Stats'
description: '⚡️ Dynamically generated stats for your github readmes'
inputs:
  username:
    description: 'GitHub Username'
    required: true
  token:
    description: 'GitHub Token'
    required: true
  theme:
    description: 'Card theme'
runs:
  using: 'node16'
  main: 'index.js'