name: Test
on: push

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Testing the action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Stats
        uses: ./stats/
        id: generate
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          username: 'Zo-Bro-23'
          theme: 'onedark'
          hide_border: 'true'
          fetch_multipage: true
          count_private: true
          include_all_commits: true
          width: 200
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: grs
          create_branch: true
          push_options: '--force'
